### ISSUE TITLE
Link on whole grid element strange behavior

### ISSUE THREAD

**Issue by jahu** [s-yadav/angulargrid#104]
I am trying to make my grid 'clickable', after clicking on whole tile of the grid I want to navigate to details of given tile:

```
<ul class="dynamic-grid" angular-grid="pics" ag-grid-width="200" performantScroll=true ag-id="gallery" ag-refresh-on-img-load="true" pageSize="1">
     <li data-ng-repeat="pic in pics" class="grid" ng-show="pic.product[6] === '0'">
	<a data-ng-href="#/product/{{pic.product[0]}}">
       <img src="{{pic.photos[0][3]}}" class="grid-img" data-actual-width = "{{pic.actualWidth}}"  data-actual-height="{{pic.actualHeight}}" />

         <h4 class="card-title text-center">{{pic.product[2]}}</h4>
         <h6 ng-hide="pic.product[5] > 0" class="card-title text-center">{{pic.product[4] | number: 0}} PLN </h6>
         <h6 ng-show="pic.product[5] > 0" class="card-title text-center lineThrough">{{pic.product[4] | number: 0}} PLN </h6>
         <h6 ng-show="pic.product[5] > 0" class="card-title text-center">{{pic.product[5] | number: 0}} PLN </h6>
       </a>
     </li>
 </ul>

```

Unfortunatelly, href values are messed up on images when grid is rendered (whereas on text attributes (h4, h6 etc) it works correct.

When hover on img link is wrong (to ....17):
![image](https://cloud.githubusercontent.com/assets/7642643/22604241/e5931aea-ea4a-11e6-82a2-162962d5bfed.png)

Whene hover on text link is OK:
![image](https://cloud.githubusercontent.com/assets/7642643/22604259/ffba369c-ea4a-11e6-9667-2802fea9373d.png)

Issue is random, but it is reproducible in 90% of cases.

Any hint appreciated.

**Comment by s-yadav** [comment]
I dont think this is related to angular grid. Why there is ** before and
after closing of anchor tag?

**Comment by s-yadav** [comment]
Ohh that was just on mail. Do you any link for it. Or can setup a codepen  for it?

**Comment by jahu** [comment]
http://lazycangoo.pl/#/shop

**Comment by s-yadav** [comment]
Issue is not related to angulargrid. It must be some logic issue on the code. Closing it.
