### ISSUE TITLE
Documentation and demo website offline

### ISSUE THREAD

**Issue by Eh1Ka6** [s-yadav/angulargrid#114]
Can't access any documentation or démo before use of your code.  

Any idea when access to it will be fixed?

**Comment by s-yadav** [comment]
Its online, can you check again.

**Comment by Eh1Ka6** [comment]
Still not 

PING ignitersworld.com (66.96.147.179) 56(84) bytes of data.

^C
--- ignitersworld.com ping statistics ---
16 packets transmitted, 0 received, 100% packet loss, time 14999ms

**Comment by s-yadav** [comment]
I can access it. Which zone u are trying from. Is your ISP or proxy server blocking anything ?

**Comment by Eh1Ka6** [comment]
Personnaly trying from Germany and my remote contact in south of France can't access it  neither

**Comment by s-yadav** [comment]
That's strange. Documentation site is hosted on some shared hosting, must be there server is offline for some zone. Will check with them. For now, you can clone the repository and try demos in the repository.

**Comment by s-yadav** [comment]
Also, you can try accessing it through some online proxy servers. That may work for you.

**Comment by Eh1Ka6** [comment]
Thanks for the answer. I'll try that

**Comment by Eh1Ka6** [comment]
Trying from Berlin  and  France
