### ISSUE TITLE
Flash of un-styled cards

### ISSUE THREAD

**Issue by acondiff** [s-yadav/angulargrid#19]
I get a flash of un-styled cards in the short amount of time angulargrid is calculating all of the top and left values and the height of the container element. I would like to set a variable on my scope to true whenever it is done rendering. A render-complete attribute would be helpful where you would pass in a variable to change to true when it is complete. This way I can set the opacity to 0 when that variable is false so the user does not see hundreds of cards stacked on top of each other.

**Comment by alereisan** [comment]
I think I had this same issue too, but ```refresh-on-img-load="true"``` did the trick

**Comment by s-yadav** [comment]
Generally its better idea to pass image dimension from ther server, and define actual-width and actual-height attribute. This way layouting need not to wait untill images are loaded. 

But if that is not possible you can check for "img-loaded" class on list item , 
Keep the opacity 0 by default, and once class is added make it to have opacity 1 .
