### ISSUE TITLE
Dynamic refresh

### ISSUE THREAD

**Issue by taylormaster** [s-yadav/angulargrid#25]
Hi!
I would like to use this plugin, because this very good :)
i have two state, list/detail. In the list view are example 10 pictures. When i upload one picture to the gallery, the list view updated, last uploaded picture the first, but the last picture in the list disappear. If i click the first picture, then go to detail view, and this picture is not this picture what i clicked.
If i refresh the browser everything work.
Do you have idea?
Thanks!

**Comment by s-yadav** [comment]
It doesn't seems to be an angulargrid issue. 
Though it will be helpful if you create a gist / jsfiddle/ plunker or can provide any demo link. So that I can understand what you are trying to achieve and what you have written for that.

**Comment by taylormaster** [comment]
i can show you with link, but need realtime chat so you understand it, it is possible?

**Comment by taylormaster** [comment]
ok, solved problem, when activating list state i wrote "angularGridInstance.gallery.refresh();"
thats work, sorry, i was careless
