### ISSUE TITLE
Add class when placed

### ISSUE THREAD

**Issue by acondiff** [s-yadav/angulargrid#26]
I would like to add a class to the element once it's top, left, and width attributes have been calculated and applied. I almost always see a flash of stacked elements. I would like to set their opacity to 0 while this is being calculated and 1 once it is complete. I am fully aware of the image-loaded class. In my case I am not dealing with images in the elements in my grid.

**Comment by s-yadav** [comment]
Hi @acondiff ,
Angulargrid do hide elements till positions are calculated. It adds angular-grid-item css to elements once positions are calculated, which make it visible.
It add following css for this
```css
.angular-grid > *{opacity : 0} 
.angular-grid > .angular-grid-item{opacity : 1}
```
You can see this on source code.
Can you check if there is any css given by yow which is overwrites opacity property for list item ?
