### ISSUE TITLE
Align all grid items to the left

### ISSUE THREAD

**Issue by mateusmcg** [s-yadav/angulargrid#29]
Your package is working perfectly and its aweome :D

And i think this is the intended behavior (to centralize the items) but i was wondering if it was possible to align all items to the left so the grid doesn't get like this:

![angulargrid](https://cloud.githubusercontent.com/assets/13169352/12184492/b74d01e0-b57c-11e5-89f7-003051581959.jpg)

HTML:

    <ul class="dynamic-grid" direction="rtol" angular-grid="vm.shows" grid-width="200" gutter-size="10" angular-grid-id="gallery" refresh-on-img-load="false" >
        <li data-ng-repeat="show in vm.shows" class="grid">
            <img ng-src="{{show.images.poster.thumb}}" data-actual-width="200px"  data-actual-height="250px" class="grid-img" />
            <div class="img-desc-wrap">
                <div class="title ng-binding">
                    {{show.title}}
                </div>
            </div>
        </li>
    </ul>

Thanks :)

**Comment by mateusmcg** [comment]
Actually i just found the problem. The 'White Collar' grid goes below the grid with the lowest height (am i right?). I just need to make sure that all grids have the same height and i'm good to go :)

Sorry for this, haha.

**Comment by s-yadav** [comment]
Yes. Keep all the height same.
Just wondering why you need angulargrid if all height are same? You can
just use float left right.

**Comment by mateusmcg** [comment]
Because i just pass my list to the model and i'm good to go, just need to do some css. So basically it is easy to use and i liked the animations.
