### ISSUE TITLE
animation failed if changed from one filtervalue to another

### ISSUE THREAD

**Issue by vollyimnetz** [s-yadav/angulargrid#3]
Hi i like your plugin very much, but it has a odd filter behavior that causes animation to fail for some case (and drive me nuts ;) ).

### How to reproduce:
0. visit http://ignitersworld.com/lab/angulargrid/index.html#demo
0.  type "Le" into the formular - wait till animation finished - you should see 4 Items
     * notice: this animation is opacity AND position
0.  add a "t" so you have "Let" - you should see 1 Item
     * notice: this animation is opacity only
0.  you may add or delete the "t" as much as you want
     * it will only animate the opacity
0.  if you change back to an empty string it will renew animate both opacity AND position

### My Problem
I want the position animation on every change of a filter (not only if i change from "no filter" to "a filter").

I think the problem is because of the elements that will be filtered out are not longer existent. After they reappear they have instantly a position (so the CSS has no value to animate from).
 
Do you have an idea how to fix?

**Comment by vollyimnetz** [comment]
I found a quick-fix, 
change
```javascript
//get all list items new height
var item, $item, clone;
for (i = 0, ln = listElms.length; i < ln; i++) {
    item = listElms[i];
    $item = single(item);
    
    //create clone of item to calculate proper height
    clone = $item.clone();
    clone.addClass('ag-no-transition');
    clone.css('width', colWidth + 'px');
    $item.after(clone);

    listElmHeights.push(clone[0].offsetHeight);
    clone.remove();
}
```
to
```javascript
//get all list items new height
var item, $item, clone;
for (i = 0, ln = listElms.length; i < ln; i++) {
    item = listElms[i];
    $item = single(item);

// ##########################################
    //define defaultValues if not set
    var reset = {
        top:'0px',
        lef:'0px'
    };
    if($item.css('top')==='auto') {
        $item.css(reset);
    }
// ##########################################
    
    //create clone of item to calculate proper height
    clone = $item.clone();
    clone.addClass('ag-no-transition');
    clone.css('width', colWidth + 'px');
    $item.after(clone);

    listElmHeights.push(clone[0].offsetHeight);
    clone.remove();
}
```

That looks a little bit better. But it would be great if we have also animations when elements are leaving the array - don't know if there is any event one can hook into.

**Comment by s-yadav** [comment]
Thanks vollyimnetz, for providing great explanation for your issue.

There is problem with filter, as ng-repeat does not trigger any event when element added or removed (there is scope watch, but will not help with this specific problem), and also it will not wait for the leaving element to complete animation, and removes them from DOM,
I guess the proper solution will be to have custom repeat directive  for the plugin, and check for model changes and listen transitionend event, for smooth transition.

I will try experimenting for the solution of this problem, it may take some time as I am quite busy with other projects, but I will try to fix this as soon as possible.

**Comment by s-yadav** [comment]
Hi vollyimnetz,
Check for the latest commit, It included animation support using ngAnimate module,
Check demo on http://ignitersworld.com/lab/angulargrid/
