### ISSUE TITLE
cols calculation assumes there is one gutter for every column (auto gridNo)

### ISSUE THREAD

**Issue by bboyle** [s-yadav/angulargrid#38]
question about the logic here: https://github.com/s-yadav/angulargrid/blob/master/angulargrid.js#L330

1 column has no gutter, 2 columns has 1 gutter (between the columns), 3 columns has 2 gutters, etc. There should be n-1 gutters.

The math for calculating cols (for auto gridNo) uses `colWidth + options.gutterSize` as if every column has a gutter. I've had to use smaller values for gridWidth in order to get the size I want. I think this calculation would work nicely if we added gutterSize to the colWidth to account for that extra gutter (which won't actually be used, it's just for the math)

`cols = options.gridNo == 'auto' ? Math.floor((contWidth + options.gutterSize) / (colWidth + options.gutterSize)) : options.gridNo,`

thoughts?

**Comment by s-yadav** [comment]
Humm.. Make sense. Don't know how I missed it.

Thanks

**Comment by bboyle** [comment]
Awesome! Thanks for the quick fix! :)
