### ISSUE TITLE
Glitches in Safari

### ISSUE THREAD

**Issue by dopgm** [s-yadav/angulargrid#4]
Hi,

Sometimes images disappear or appear compressed horizontally .
<img width="1582" alt="screen shot 2015-07-24 at 2 16 08 am" src="https://cloud.githubusercontent.com/assets/6718777/8868785/2bcb1ed2-31aa-11e5-8614-081c3932c4bb.png">

Mac OS 10.10.4
Safari 8.0.7

**Comment by s-yadav** [comment]
Fixed now.
