### ISSUE TITLE
Its possible use nested grids?

### ISSUE THREAD

**Issue by exejutable** [s-yadav/angulargrid#46]
I want to use this library not for images. I have two  ng-repeats with variable length its posibble this?

**Comment by s-yadav** [comment]
Yes it is possible.

**Comment by DHoffm** [comment]
I suppose it is not necessary for the nested layout to be animated:

I setup a demo with a nested grid based on css3 column attributes:
https://plnkr.co/edit/hRCmYkgHsVtvYq91dKgE?p=preview

**Comment by exejutable** [comment]
This is very hellpfull thanks @DHoffm.
