### ISSUE TITLE
Integrating with MEAN.JS framework

### ISSUE THREAD

**Issue by bighaj** [s-yadav/angulargrid#49]
I think I have a problem with how I've integrated your controller (index.js) into my framework - I'll paste the code below. The error I'm receiving is:

Error: [$injector:unpr] Unknown provider: ngMaterialProvider <- ngMaterial <- MainCtrl
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=ngMaterialProvider%20%3C-%20ngMaterial%20%3C-%20MainCtrl
    at http://localhost:3000/lib/angular/angular.js:68:12
    at http://localhost:3000/lib/angular/angular.js:4418:19
    at Object.getService [as get] (http://localhost:3000/lib/angular/angular.js:4571:39)
    at http://localhost:3000/lib/angular/angular.js:4423:45
    at getService (http://localhost:3000/lib/angular/angular.js:4571:39)
    at injectionArgs (http://localhost:3000/lib/angular/angular.js:4595:58)
    at Object.instantiate (http://localhost:3000/lib/angular/angular.js:4637:18)
    at $controller (http://localhost:3000/lib/angular/angular.js:10042:28)
    at http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:4081:28
    at invokeLinkFn (http://localhost:3000/lib/angular/angular.js:9623:9) <div data-ui-view="" autoscroll="false" ng-class="app.viewAnimation" class="content-wrapper ng-scope">

Here's the index.js file:
(function() {
    'use strict';

    angular.module('app.core').controller('MainCtrl', MainCtrl);

    MainCtrl.$inject = ['$scope', '$http', '$q','ngMaterial','angularGrid'];
    function MainCtrl($scope, $http, $q,ngMaterial,angularGrid) {
  var vm = this;

        activate();

        ////////////////

function activate() {

  //var vm = this;
  $scope.card = {};
  $scope.card.title = 'test';
  vm.page = 0;
  vm.shots = [];
  vm.loadingMore = false;

  vm.loadMoreShots = function() {

    if(vm.loadingMore) return;
    vm.page++;
    // var deferred = $q.defer();
    vm.loadingMore = true;
    var promise = $http.get('https://api.dribbble.com/v1/shots/?per_page=24&page='+vm.page+'&access_token=3df6bcfc60b54b131ac04f132af615e60b0bd0b1cadca89a4761cd5d125d608f');
    promise.then(function(data) {

      var shotsTmp = angular.copy(vm.shots);
      shotsTmp = shotsTmp.concat(data.data);
      vm.shots = shotsTmp;
      vm.loadingMore = false;

    }, function() {
      vm.loadingMore = false;
    });
    return promise;
  };

  vm.loadMoreShots();

};
};
//MainCtrl.filter('unsafe', function($sce) { return $sce.trustAsHtml; });

})();

**Comment by simison** [comment]
Hi! Your error has nothing to with AngularGrid. This is your issue:

>Unknown provider: ngMaterialProvider <- ngMaterial

Make sure you've included and configured https://material.angularjs.org/ correctly.
