### ISSUE TITLE
Problem when refreshing the page.

### ISSUE THREAD

**Issue by celsomtrindade** [s-yadav/angulargrid#5]
I did tried the solution metioned in the doc, but it still doesn't work, even when i try to do like in your example.

If i refresh the page, it doesn't work.

Here is what i did:

**html**:

	<div class="col-lg-12" my-portfolio >
		<ul class="dynamic-grid" angular-grid="pics" grid-width="300" gutter-size="10" angular-grid-id="gallery" refresh-on-img-load="false" >
			<li data-ng-repeat="port in pagedPortfolio.data" class="grid">
				<img src="{{port.img[0]}}" class="grid-img" />
				<p>{{port.title}}</p>
			</li>
		</ul>
	</div>

**app.js**

	.controller('PortfolioCtrl', ['$scope','angularGridInstance', function ($scope,angularGridInstance){
		$scope.pagename = "Portfolio";
		$scope.refresh = function(){
			angularGridInstance.gallery.refresh();
		}
	}])

Can you provide a better example? Or a way to fix it?

***Edit***: Btw, I'm loading my data with a `directive/factory` but even using the refresh there, it doesn't work. Like so:

	.directive('myPortfolio', ['mainFactory','angularGridInstance', function (mainFactory,angularGridInstance) {
		return {
			restrict: "A",
			link: function($scope) {
				mainFactory.getPortfolio().then(function(data) {
					$scope.pagedPortfolio = data;
					angularGridInstance.gallery.refresh();
				})
			}
		}
	}])

**Comment by s-yadav** [comment]
You should mention actual width and dimension of an image if you are setting refresh-on-img-load="false" . See example http://ignitersworld.com/lab/angulargrid/

Or just remove refresh-on-img-load="false"  from your ul .
