### ISSUE TITLE
Integrate with angular-ui/ui-sortable

### ISSUE THREAD

**Issue by imwithye** [s-yadav/angulargrid#53]
Hi i am implementing a method which supports reorder the card in the grad view. I'd like to use [angular-ui/ui-sortable](https://github.com/angular-ui/ui-sortable) to support drag and drop sorting. But it seems angulargrid conflicts with that library. Any alternative way to do?

**Comment by s-yadav** [comment]
Can you create a sample jsfiddle / codepen for it. It will be easier to give any solution then.

**Comment by s-yadav** [comment]
Looks like ui-sortable and angulargrid both have isolated scope which causes conflict. Though a fiddle will be helpful. 
Closing it. Open if anyone else get into this issue.
