### ISSUE TITLE
Work with two kind of items

### ISSUE THREAD

**Issue by mavillar** [s-yadav/angulargrid#54]
Hi,

I'm working with angulargrid perfectly. It's works like a charm!

I'm dealing with the possibility of having two kind of items. With this I mean that all items are always the with the same aspect and now I need to be able to add a new item with it's own aspect.

Let's suppose I have a list of Houses and I display a list of 20 items in the page. What I need is just to be able to include among the other main 20 items, one new item that show an Offer, promotion or something similar. As you can see, this new item has it's own size, different than the other 20 items.

Is it possible? if yes, how can I accomplish this?

**Comment by s-yadav** [comment]
Yes it is possible. You just update the model array, ie (add a new item in middle or any where) , angulargrid will adapt it.

**Comment by guidodipaolo** [comment]
Hi I want to do something similar but I dont know how to do it. 
I have used the Angular Pinterest Grid to show some products. 
All this products has a 200px of weight, while other blocks (where I will show Adsense Ads) has 336 px. There is any possibility to define two kinds of width on the same grid ? 

Thanks !!
