### ISSUE TITLE
Using angular material md-card instead of .card look alike in infiniteScroll demo breaks angulargrid

### ISSUE THREAD

**Issue by chrismarx** [s-yadav/angulargrid#58]
Is this a known issue? Is that why the md-card wasn't used in the first place? The problem that arises is that the cloned divs aren't removed reliably, causing the height of the scroll to be wonky. If you think there is a solution to this, I can post a md-card version of the infiniteScroll demo from the repo, which clearly illustrates the problem-

**Comment by chrismarx** [comment]
I can change the title of the issue if desired, I think I narrowed down the problem. If I include the image as an img element, I get the same problem, even just using and img element in the original demo. Seems like it only works with the images set  as background-image. Any ideas why?

**Comment by cm325** [comment]
Upon further investigation, it appears that using the <img> was the problem, not the md-card. I have it working with md-card, but had to use a background-image

**Comment by s-yadav** [comment]
I guess this issue has been solved. Closing it. Open again with a fiddle if it still exist.
