### ISSUE TITLE
dynamic-grid margin

### ISSUE THREAD

**Issue by mhipo1364** [s-yadav/angulargrid#6]
Hi

Thanks for this awesome package, I wanna set `margin-left`, `margin-right` to whole grid container, how can I do this?

**Comment by s-yadav** [comment]
You just give margin-left and margin-right to container "dynamic-grid" it will not affect the plugin.

**Comment by mhipo1364** [comment]
Yes, thanks, I put the whole elements in  container which have margin :+1:
