### ISSUE TITLE
Adding list view mode, and varios width for desctop and mobile media.

### ISSUE THREAD

**Issue by sergeDEsun** [s-yadav/angulargrid#61]
**Thanks so much for this directive. It's a very useful tool!**
It would be great if was possibility of layout changing from grid to simple list.
And if user can set one item width for desctop(>1024) and another for mobile (<1024)
For example:
```
desctop screen = 1280
d_width = 250 => 1280/250 = 5 items (minimal)
mobile screen = 300
m_width = 100 => 300/100 = 3 items (minimal)
```

**Comment by s-yadav** [comment]
You can calculate gridWidth based window width in your controller and assign to scope. You can pass that scope as gridWidth attributes value.
