### ISSUE TITLE
Cannot read property 'length' of undefined in line 300

### ISSUE THREAD

**Issue by yuens1002** [s-yadav/angulargrid#63]
i'm using angularGrid.js v 0.6.0 and i'm getting the following errors in the console when i'm just scrolling the page, doesn't seem to have effect on the page visually.  

Uncaught TypeError: Cannot read property 'length' of undefined

infiniteScroll @ angulargrid.js:300
scrollHandler @ angulargrid.js:317
jQuery.event.dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121

**Comment by evi-in-tunis** [comment]
Yep, same here.

**Comment by yuens1002** [comment]
Okay.  I think you need to make sure the name of the model you're using is
correct.  I resloved the issue after that...

**Comment by s-yadav** [comment]
@yuens1002  Hope its solved now.
