### ISSUE TITLE
need a way to reflow the tiles triggered by ng-show

### ISSUE THREAD

**Issue by yuens1002** [s-yadav/angulargrid#64]
hi there, i have a list in each of the tiles that shows and hides using ng-show trigged by ng-clicked.  is there a way to call angularGridInstance in my controller that sees showIngList which i hope would reflow the tiles each time ng-show is invoked.  

ng-click trigger
```
<span class="h4">{{eachRecipe.recipe.ingredientLines.length}}</span> Ingredients <a href ng-click="showIngList = !showIngList"><span class="h4"><span class="glyphicon glyphicon-menu-down"></span></span></a>
``` 

ng-show list
```
<ul><li ng-show="!showIngList" ng-repeat="listIngredient in eachRecipe.recipe.ingredientLines">{{listIngredient}}</li></ul> 
```

**Comment by s-yadav** [comment]
ng-show / ng-filter does not change model which is responsible for adding list item, thus angular grid can't be notified to reflow elements. You have to manually watch showIngList model and trigger angular grid refresh. See Refreshing manually in http://ignitersworld.com/lab/angulargrid/ .
