### ISSUE TITLE
codepen with version 0.6.0

### ISSUE THREAD

**Issue by payalpatel2299** [s-yadav/angulargrid#65]
Hey Yadav,

Thanks for creating this.

can you please update your http://codepen.io/s-yadav/pen/EPoOZo with new version of library 0.6.0
 I am trying but getting issue with it. and can not debug it.

Thanks

**Comment by s-yadav** [comment]
@payalpatel2299  Update codepen with latest version.

**Comment by langfors** [comment]
Also note, because of #72, I've had to fork the codepen to get it working again:

http://codepen.io/langfors/pen/PGjavj
