### ISSUE TITLE
Infinite Scroll with ngInclude and $compile

### ISSUE THREAD

**Issue by SandeepPotti** [s-yadav/angulargrid#70]
I had to load my html dynamically using ngInclude and using $compile for compiling the same. 
Now the problem is that, the scroll event is not fired and inturn 'Infinite scroll' is not invoked. Any inputs to solve this would be great. Thank you.

**Comment by jvieyra92** [comment]
Have you seen this example? Works fine for me. 
http://codepen.io/s-yadav/pen/EPoOZo

**Comment by s-yadav** [comment]
@SandeepPotti  Problem shouldn't be nginclude or compile. I think you have not properly defined scroll container. Can you setup a demo or jsfiddle so I can look into it.

**Comment by SandeepPotti** [comment]
@s-yadav thanks for the reply. I would go through codepen of @jvieyra92  and ll set up a demo incase im having issue. Cheers.

**Comment by SandeepPotti** [comment]
@s-yadav,Scroll started working when correct Contianed Id is entered. Thank you.
