### ISSUE TITLE
Refresh the grid manaully

### ISSUE THREAD

**Issue by jvieyra92** [s-yadav/angulargrid#71]
I have a search bar above my grid that pulls data from the backend depending on whats enter in the search bar.  On first load the cards load fine, but once I enter text into the search, I get the correct results back but the cards are all hidden. Then if I resize the page the cards appear. I looked at the console and I'm getting this error "TypeError: h.model is undefined: 	...meout),B.isLoading=!1}function z(o){if(!B.isLoading&&h.model.length){var n=B.scr..." for AngularJS.

A quick fix for this is to just refresh the grid manually after every call. Does anyone know how to do that? 

If someone knows the real reason this happens and knows how to fix it, I'd be glad to try that too. Thanks!

**Comment by s-yadav** [comment]
Can you try to follow Refreshing manually and Handeling search, filter and sorting section in doc (http://ignitersworld.com/lab/angulargrid/). Let me know if still get the issue.

**Comment by jvieyra92** [comment]
Thanks, but it didn't work.  I injected angularGridInstance into my controller and called angularGridInstance.gallery.refresh(); but the images in the cards didn't refresh.
This is what the settings are for the angular gird 

`<md-content class="md-padding " layout-xs="column" layout="row" layout-align="center center" id="gallery" ng-cloak>
<div angular-grid="vm.dataArray" ag-grid-width="500" ag-gutter-size="20"
                 ag-id="gallery" ag-scroll-container="'#gallery'" ag-infinite-scroll="vm.loadMore($event)"
                 ag-infinite-scroll-distance="50">`

**Comment by jvieyra92** [comment]
Thanks "angularGridInstance.gallery.refresh()" works with refreshing my images but it doesn't seem to refresh the grid in terms of its layout. For example, I have a textarea inside the cards and as the the textarea grows the card to grow and overlaps the lower card. I call angularGridInstance.gallery.refresh() but the grid layout stays the same.

**Comment by s-yadav** [comment]
Or you can do angularGridInstance.youragid.refresh()
