### ISSUE TITLE
Unable to render items when object is re-initiated

### ISSUE THREAD

**Issue by SandeepPotti** [s-yadav/angulargrid#76]
In my case, I will have to reset the object to its initial state after some modifications. for this I am maintaining a copy and assigning back to the object when required (using angular.copy). But when i reset the object, angular grid is unable to render any thing.  Can you please provide me any solution.

**Comment by s-yadav** [comment]
It should work till you are having same model name. Can you post your js code, or set a jsfiddle.

**Comment by awener** [comment]
Can confirm it. To test it use infinitescroll and instead of appending main model just rewrite it
vm.pics = item.result;
Data gets loaded to dom, but it's hidden for some reason.

`var cloneCss = {
    visibility: 'hidden',
    opacity: 0,
    top: 0,
    left: 0,
    width: ''
  };`

If you change it to visible and remove opacity you can sort of see it.
