### ISSUE TITLE
empty white space getting added at the bottom

### ISSUE THREAD

**Issue by mastercod3r** [s-yadav/angulargrid#77]
Sometimes when scrolling, the scroll container heigh increases but the content does not loads, leaving a lot of white space at the bottom. Is there a way to handle that?
Also, removing md-content, breaks the infinite scroll. I dont want much dependency on ngMaterial.

Can you throw some light on how the height of the div increases so that I can find the bug?

**Comment by s-yadav** [comment]
@mastercod3r  There is no dependecy with ngMaterial. It just on demo. You have to make sure you give proper scrollContainer attribute.

**Comment by mastercod3r** [comment]
Doing an overflow:hidden solves it.
