### ISSUE TITLE
ag-infinite-scroll-distance works as pixels not percentage

### ISSUE THREAD

**Issue by vsc-github** [s-yadav/angulargrid#78]
I want to preload the cards before the user reaches bottom for a better infinite scroll experience. So I set ag-infinite-scroll-distance=50 thinking it would make the next page call at 50% of the scroll height from bottom. But it doesnt work. It worked better when I used 800. But that kind of stops working after 7-8 scrolls. 

Is there any workaround? Or am I doing something wrong?

**Comment by s-yadav** [comment]
Yes it works with pixels. I am not sure why it stopped working afetr 7/8 scrolls. It will be helpful if you can setup a  fiddle.
