### ISSUE TITLE
Potential infinite loop in getColWidth function

### ISSUE THREAD

**Issue by nkovacic** [s-yadav/angulargrid#88]
If width on line [336](https://github.com/s-yadav/angulargrid/blob/master/angulargrid.js#L336) is for any reason 0, which happens if the directive is destroyed before it calculates width but the elements are still present (eg. when ui-router changes state), then an infinite loop occurs because no in line [340](https://github.com/s-yadav/angulargrid/blob/master/angulargrid.js#L340) becomes infinite and then line [408](https://github.com/s-yadav/angulargrid/blob/master/angulargrid.js#L408) crashes the application.
This bug only happens when cssGrid option is true.

**Comment by nkovacic** [comment]
Made a [pull request](https://github.com/s-yadav/angulargrid/pull/89)

**Comment by s-yadav** [comment]
Merged

**Comment by nkovacic** [comment]
A quick publish to npm for the latest fixes? :)

**Comment by s-yadav** [comment]
@nkovacic  Done.
