### ISSUE TITLE
Integration with twitter bootstrap  ?

### ISSUE THREAD

**Issue by phuyem** [s-yadav/angulargrid#9]
Hi,

Your plugin looks cool. But is there a way to use it with twitter bootstrap? Something like: 

     <div class="masonry-grid row dynamic-grid" angular-grid="posts"  >
        
           <div class=" grid masonry-grid-item   col-sm-6 " ng-repeat='post in posts'>
 
                 <htmlcontenthere class="clearfix blogpost">
                 ..............
                 </htmlcontenthere>
            </div>
     </div>

This one works on desktop and iphone 6, not on iphone 4-5  , some other small devices...

**Comment by s-yadav** [comment]
There is no bootstrap support for now, it uses grid-width and gutter-size attribute to determine width, plugin try to match grid width as minimum width value and number of columns are decided based on available space.

Will keep this issue open, so if there is any plan for bootstrap integration.

**Comment by j-m-davison** [comment]
I've had lots of success using bootstrap within the "html goes here" for what its worth
