### ISSUE TITLE
Issue with image within ng-include

### ISSUE THREAD

**Issue by jaideepdas** [s-yadav/angulargrid#95]
If image tag is with a ng-include then angulargrid doesn't detect image loading and fails to refresh. Is there way around this issue.

**Comment by s-yadav** [comment]
Right now angulargrid does not work with ng-include. You can add them either directly or create a synchronous directive. I will add this on documentation. 
Ng-include asynchronously loads template, and angulargrid does not get notified about template has been loaded.
