### ISSUE TITLE
How to refresh new added images only rather than refresh all images?

### ISSUE THREAD

**Issue by tim7004** [s-yadav/angulargrid#97]
Dear All,
I am using angulargrid to display my images which is over 1000+. At the beginning, 50 images will be shown. Then 50 more images will be shown when I scroll down. But it becomes slower and slower when I keep slowing down. I found that the it will refresh all images when the new images are added. How can I refresh new added images only rather than refresh all images?

Thank you.

**Comment by s-yadav** [comment]
Use performant scroll option. See the doc
